### ISSUE TITLE
Will there be a support for nolf2?

### ISSUE THREAD

**Issue by lightmonolight** [Five-Damned-Dollarz/io_scene_jupex#4]
Will there be a support for nolf2?

**Comment by Five-Damned-Dollarz** [comment]
NOLF2 is based on the Jupiter engine, not Jupiter Ex. While technically FEAR 2/Condemned are based on a the Loki version, they are significantly closer than Jupiter is to Jupiter Ex.
Maybe in the future I'll either write a separate Jupiter plugin, or expand the scope of this to more versions of LithTech, but for now I have no plans to support Jupiter, sorry.
